#!/usr/bin/env node
/**
 * Re-applies the OneSignal Notification Service Extension setup after every
 * `cordova prepare` (which `ionic cordova build ios` runs).
 *
 * cordova-ios 5's prepare.js calls xcode's updateBuildProperty() without a
 * target filter, so PRODUCT_BUNDLE_IDENTIFIER is stamped onto *every* build
 * configuration in the project - including the extension's. An .appex sharing
 * its parent's bundle id fails to install:
 *
 *     MIInstallerErrorDomain 57 / DuplicateIdentifier
 *     "The parent bundle has the same identifier ... as sub-bundle ...appex"
 *
 * prepare can also regenerate the Podfile and Xcode can reset objectVersion,
 * so all four fixups live here. Everything is idempotent - the hook is a no-op
 * once the project is already correct.
 *
 * See ios-onesignal-nse/README.md for the one-time Xcode target creation.
 */

var fs = require('fs');
var path = require('path');
var execSync = require('child_process').execSync;

var NSE = 'OneSignalNotificationServiceExtension';

module.exports = function (context) {
  var root = context.opts.projectRoot;
  var iosDir = path.join(root, 'platforms', 'ios');
  if (!fs.existsSync(iosDir)) return;

  var pbxproj = findPbxproj(iosDir);
  if (!pbxproj) return;

  var proj = fs.readFileSync(pbxproj.path, 'utf8');
  // Nothing to do if the extension target was never added in Xcode.
  if (proj.indexOf(NSE) === -1) return;

  var appId = readWidgetId(root);
  if (!appId) return;

  var changed = false;

  // 1. objectVersion 70 (Xcode 26 default) is unreadable by xcodeproj 1.27 /
  //    CocoaPods 1.16. 77 is understood by both.
  if (proj.indexOf('objectVersion = 70;') !== -1) {
    proj = proj.replace('objectVersion = 70;', 'objectVersion = 77;');
    changed = true;
    log('objectVersion -> 77');
  }

  // 2 + 3. Per-target settings on the extension's Debug/Release configs.
  var nseIds = extensionConfigIds(proj);
  nseIds.forEach(function (id) {
    var res = patchConfig(proj, id, appId);
    if (res.changed) {
      proj = res.text;
      changed = true;
      res.notes.forEach(log);
    }
  });

  if (changed) fs.writeFileSync(pbxproj.path, proj);

  // 4. The Podfile is regenerated by prepare, dropping the extension target.
  if (ensurePodfileTarget(iosDir, pbxproj.name)) {
    log('re-added ' + NSE + ' target to Podfile, running pod install');
    try {
      execSync('pod install', {
        cwd: iosDir,
        stdio: 'inherit',
        // CocoaPods on the system Ruby 2.6 aborts without a UTF-8 locale.
        env: Object.assign({}, process.env, { LANG: 'en_US.UTF-8' })
      });
    } catch (e) {
      log('pod install FAILED - run it by hand in platforms/ios');
    }
  }

  // 5. Keep the tracked extension sources authoritative. The Xcode template
  //    ships the SDK 5.x API (import OneSignalExtension), which does not exist
  //    in the 2.16.1 SDK that onesignal-cordova-plugin 2.11.2 installs.
  syncTrackedSources(root, iosDir);
};

function log(msg) {
  console.log('onesignal-nse: ' + msg);
}

function findPbxproj(iosDir) {
  var dir = fs.readdirSync(iosDir).filter(function (f) {
    return /\.xcodeproj$/.test(f);
  })[0];
  if (!dir) return null;
  var p = path.join(iosDir, dir, 'project.pbxproj');
  return fs.existsSync(p) ? { path: p, name: dir } : null;
}

function readWidgetId(root) {
  var cfg = path.join(root, 'config.xml');
  if (!fs.existsSync(cfg)) return null;
  var m = /<widget[^>]*\sid="([^"]+)"/.exec(fs.readFileSync(cfg, 'utf8'));
  return m ? m[1] : null;
}

// UUIDs of the XCBuildConfiguration entries belonging to the extension's
// build configuration list.
function extensionConfigIds(proj) {
  var listRe = new RegExp(
    '\\/\\* Build configuration list for PBXNativeTarget "' + NSE +
    '" \\*\\/ = \\{([\\s\\S]*?)\\};'
  );
  var list = listRe.exec(proj);
  if (!list) return [];
  var ids = [];
  var idRe = /([0-9A-F]{24}) \/\* (?:Debug|Release) \*\//g;
  var m;
  while ((m = idRe.exec(list[1])) !== null) ids.push(m[1]);
  return ids;
}

function patchConfig(proj, id, appId) {
  var start = proj.indexOf(id + ' /* ');
  if (start === -1) return { changed: false };
  var open = proj.indexOf('buildSettings = {\n', start);
  if (open === -1) return { changed: false };
  var bodyStart = open + 'buildSettings = {\n'.length;
  var bodyEnd = proj.indexOf('\t\t\t};', bodyStart);
  if (bodyEnd === -1) return { changed: false };

  var body = proj.slice(bodyStart, bodyEnd);
  var notes = [];
  var wantId = appId + '.' + NSE;
  var wantEnt = NSE + '/' + NSE + '.entitlements';

  // prepare.js flattens this to the parent's id -> DuplicateIdentifier at install.
  var idRe = /(\t+PRODUCT_BUNDLE_IDENTIFIER = )([^;]+);/;
  if (idRe.test(body)) {
    if (idRe.exec(body)[2] !== wantId) {
      body = body.replace(idRe, '$1' + wantId + ';');
      notes.push('PRODUCT_BUNDLE_IDENTIFIER -> ' + wantId);
    }
  } else {
    body = '\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = ' + wantId + ';\n' + body;
    notes.push('added PRODUCT_BUNDLE_IDENTIFIER = ' + wantId);
  }

  // App Groups capability, shared with the app for the badge count.
  if (body.indexOf('CODE_SIGN_ENTITLEMENTS') === -1) {
    body = '\t\t\t\tCODE_SIGN_ENTITLEMENTS = ' + wantEnt + ';\n' + body;
    notes.push('added CODE_SIGN_ENTITLEMENTS');
  }

  if (!notes.length) return { changed: false };
  return {
    changed: true,
    text: proj.slice(0, bodyStart) + body + proj.slice(bodyEnd),
    notes: notes
  };
}

function ensurePodfileTarget(iosDir, projName) {
  var p = path.join(iosDir, 'Podfile');
  if (!fs.existsSync(p)) return false;
  var podfile = fs.readFileSync(p, 'utf8');
  if (podfile.indexOf("target '" + NSE + "'") !== -1) return false;

  // Must be the same pod version as the app target - OneSignal does not
  // support a 2.x app with a 5.x extension.
  var version = /pod 'OneSignal', '([^']+)'/.exec(podfile);
  if (!version) return false;

  podfile += "\ntarget '" + NSE + "' do\n" +
    "\tproject '" + projName + "'\n" +
    "\tpod 'OneSignal', '" + version[1] + "'\n" +
    'end\n';
  fs.writeFileSync(p, podfile);
  return true;
}

function syncTrackedSources(root, iosDir) {
  var src = path.join(root, 'ios-onesignal-nse');
  var dest = path.join(iosDir, NSE);
  if (!fs.existsSync(src) || !fs.existsSync(dest)) return;

  ['NotificationService.swift', 'Info.plist', NSE + '.entitlements'].forEach(function (f) {
    var from = path.join(src, f);
    if (!fs.existsSync(from)) return;
    var to = path.join(dest, f);
    var want = fs.readFileSync(from);
    if (fs.existsSync(to) && fs.readFileSync(to).equals(want)) return;
    fs.writeFileSync(to, want);
    log('restored ' + f);
  });
}
